apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: custom-fastapi-service
spec:
  template:
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/projectx-298909/proxima-registry/fastapi-app:latest
          env:
          ports:
            - containerPort: 8080